// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyGuidance.Infrastructure;

#nullable disable

namespace StudyGuidance.Infrastructure.Migrations
{
    [DbContext(typeof(StudyGuidanceDbContext))]
    [Migration("20231031144809_DomainQuestion")]
    partial class DomainQuestion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudyGuidance.Domain.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Content = "AI",
                            QuestionId = -1
                        },
                        new
                        {
                            OptionId = 2,
                            Content = "Development",
                            QuestionId = -1
                        },
                        new
                        {
                            OptionId = 3,
                            Content = "Software Engineering",
                            QuestionId = -1
                        },
                        new
                        {
                            OptionId = 4,
                            Content = "Systeem en netwerkbeheer",
                            QuestionId = -1
                        },
                        new
                        {
                            OptionId = 5,
                            Content = "Data",
                            QuestionId = -1
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = -1,
                            Phrase = "In welk domein interesseer je je?"
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Option", b =>
                {
                    b.HasOne("StudyGuidance.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyGuidance.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
