// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyGuidance.Infrastructure;

#nullable disable

namespace StudyGuidance.Infrastructure.Migrations
{
    [DbContext(typeof(StudyGuidanceDbContext))]
    [Migration("20231214145338_updateTestamonials")]
    partial class updateTestamonials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudyGuidance.Domain.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionRelation")
                        .HasColumnType("int");

                    b.Property<int>("StudyCourseRelation")
                        .HasColumnType("int");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WorkInTeam")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnSite")
                        .HasColumnType("bit");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "Tester",
                            OptionRelation = 15,
                            StudyCourseRelation = 1,
                            SubDomain = "Software analysis",
                            WorkInTeam = false,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "QA Engineer",
                            OptionRelation = 14,
                            StudyCourseRelation = 2,
                            SubDomain = "Project Management",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "Business Analyst",
                            OptionRelation = 15,
                            StudyCourseRelation = 3,
                            SubDomain = "Software analysis",
                            WorkInTeam = true,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "Functional Analyst",
                            OptionRelation = 15,
                            StudyCourseRelation = 4,
                            SubDomain = "Software analysis",
                            WorkInTeam = true,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Application Support",
                            OptionRelation = 11,
                            StudyCourseRelation = 5,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "Helpdesk",
                            OptionRelation = 14,
                            StudyCourseRelation = 6,
                            SubDomain = "Project Management",
                            WorkInTeam = false,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "PHP Developer",
                            OptionRelation = 13,
                            StudyCourseRelation = 6,
                            SubDomain = "Backend",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Drupal Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 7,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Cobol Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 8,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Dynammics Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 9,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Java Developer",
                            OptionRelation = 13,
                            StudyCourseRelation = 10,
                            SubDomain = "Backend",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 12,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "SAP Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 11,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 13,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Siebel Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 12,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 14,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "RPG developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 13,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 15,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "System admin",
                            OptionRelation = 18,
                            StudyCourseRelation = 14,
                            SubDomain = "Networking",
                            WorkInTeam = false,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 16,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "Network engineer",
                            OptionRelation = 18,
                            StudyCourseRelation = 15,
                            SubDomain = "Networking",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 17,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Data",
                            Name = "Data migration expert",
                            OptionRelation = 22,
                            StudyCourseRelation = 1,
                            SubDomain = "Analyst",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 18,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Data",
                            Name = "Data architect",
                            OptionRelation = 22,
                            StudyCourseRelation = 2,
                            SubDomain = "Analyst",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 19,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Data",
                            Name = "Database administrator",
                            OptionRelation = 22,
                            StudyCourseRelation = 3,
                            SubDomain = "Analyst",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 20,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "AWS DevOps Engineer",
                            OptionRelation = 16,
                            StudyCourseRelation = 4,
                            SubDomain = "Automation",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 21,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "Project manager",
                            OptionRelation = 14,
                            StudyCourseRelation = 5,
                            SubDomain = "Project Management",
                            WorkInTeam = true,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 22,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "Azure DevOps Engineer",
                            OptionRelation = 16,
                            StudyCourseRelation = 6,
                            SubDomain = "Automation",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 23,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "SharePoint Developer",
                            OptionRelation = 11,
                            StudyCourseRelation = 7,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 24,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = ".NET Developer",
                            OptionRelation = 13,
                            StudyCourseRelation = 8,
                            SubDomain = "Backend",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 25,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Frontend Developer",
                            OptionRelation = 12,
                            StudyCourseRelation = 9,
                            SubDomain = "Frontend",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 26,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Software Architect",
                            OptionRelation = 11,
                            StudyCourseRelation = 10,
                            SubDomain = "Fullstack",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 27,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Development",
                            Name = "Development Team Lead",
                            OptionRelation = 11,
                            StudyCourseRelation = 11,
                            SubDomain = "Fullstack",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 28,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Software Management",
                            Name = "SCRUM Master",
                            OptionRelation = 14,
                            StudyCourseRelation = 12,
                            SubDomain = "Project Management",
                            WorkInTeam = true,
                            WorkOnSite = true
                        },
                        new
                        {
                            JobId = 29,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "Security Engineer",
                            OptionRelation = 17,
                            StudyCourseRelation = 13,
                            SubDomain = "Security",
                            WorkInTeam = false,
                            WorkOnSite = false
                        },
                        new
                        {
                            JobId = 30,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Domain = "Systeem en netwerkbeheer",
                            Name = "PEN Tester",
                            OptionRelation = 17,
                            StudyCourseRelation = 14,
                            SubDomain = "Security",
                            WorkInTeam = false,
                            WorkOnSite = true
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("OptionRelation")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Content = "AI",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            Content = "Development",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            Content = "Software Management",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            Content = "Systeem en netwerkbeheer",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 5,
                            Content = "Elektronica",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 6,
                            Content = "Data",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 7,
                            Content = "VR & AR",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 8,
                            Content = "AI Robotics",
                            IsChecked = false,
                            OptionRelation = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 9,
                            Content = "Machine Learning",
                            IsChecked = false,
                            OptionRelation = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 10,
                            Content = "Computer Vision",
                            IsChecked = false,
                            OptionRelation = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 11,
                            Content = "Fullstack",
                            IsChecked = false,
                            OptionRelation = 2,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 12,
                            Content = "Frontend",
                            IsChecked = false,
                            OptionRelation = 2,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 13,
                            Content = "Backend",
                            IsChecked = false,
                            OptionRelation = 2,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 14,
                            Content = "Project Management",
                            IsChecked = false,
                            OptionRelation = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 15,
                            Content = "Software analysis",
                            IsChecked = false,
                            OptionRelation = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 16,
                            Content = "Automation",
                            IsChecked = false,
                            OptionRelation = 4,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 17,
                            Content = "Security",
                            IsChecked = false,
                            OptionRelation = 4,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 18,
                            Content = "Networking",
                            IsChecked = false,
                            OptionRelation = 4,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 19,
                            Content = "Elektronica-ICT",
                            IsChecked = false,
                            OptionRelation = 5,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 20,
                            Content = "Internet of Things",
                            IsChecked = false,
                            OptionRelation = 5,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 21,
                            Content = "Elektromechanica",
                            IsChecked = false,
                            OptionRelation = 5,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 22,
                            Content = "Analyst",
                            IsChecked = false,
                            OptionRelation = 6,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 23,
                            Content = "Data AI",
                            IsChecked = false,
                            OptionRelation = 6,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 24,
                            Content = "VR",
                            IsChecked = false,
                            OptionRelation = 7,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 25,
                            Content = "AR",
                            IsChecked = false,
                            OptionRelation = 7,
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 26,
                            Content = "Ja",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 27,
                            Content = "Nee",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 28,
                            Content = "Ja",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 29,
                            Content = "Nee",
                            IsChecked = false,
                            OptionRelation = 0,
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Phrase = "In welk domein heb je interesse?",
                            QuestionType = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            Phrase = "In welk subdomein heb je interesse?",
                            QuestionType = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Phrase = "Werk je graag vaak in groep?",
                            QuestionType = 0
                        },
                        new
                        {
                            QuestionId = 4,
                            Phrase = "Reis je graag voor je werk?",
                            QuestionType = 0
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.StudyCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DiplomaType")
                        .HasColumnType("int");

                    b.Property<int>("JobRelation")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Study")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudyCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiplomaType = 0,
                            JobRelation = 1,
                            Location = 0,
                            School = "Syntra",
                            Study = "Switch2It"
                        },
                        new
                        {
                            Id = 2,
                            DiplomaType = 0,
                            JobRelation = 1,
                            Location = 0,
                            School = "Hogeschool PXL",
                            Study = "Toegpaste Informatica"
                        },
                        new
                        {
                            Id = 3,
                            DiplomaType = 1,
                            JobRelation = 1,
                            Location = 0,
                            School = "Hogeschool PXL",
                            Study = "Elektronica-ICT"
                        },
                        new
                        {
                            Id = 4,
                            DiplomaType = 2,
                            JobRelation = 1,
                            Location = 1,
                            School = "KU Leuven",
                            Study = "Master: Toegepaste Informatica"
                        },
                        new
                        {
                            Id = 5,
                            DiplomaType = 1,
                            JobRelation = 2,
                            Location = 1,
                            School = "KU Leuven",
                            Study = "Biomedische Wetenschappen"
                        },
                        new
                        {
                            Id = 6,
                            DiplomaType = 2,
                            JobRelation = 3,
                            Location = 2,
                            School = "VUB",
                            Study = "Master in Business Administration"
                        },
                        new
                        {
                            Id = 7,
                            DiplomaType = 0,
                            JobRelation = 3,
                            Location = 3,
                            School = "Artesis Plantijn Hogeschool",
                            Study = "Marketing Management"
                        },
                        new
                        {
                            Id = 8,
                            DiplomaType = 1,
                            JobRelation = 4,
                            Location = 4,
                            School = "UGent",
                            Study = "Communication Sciences"
                        },
                        new
                        {
                            Id = 9,
                            DiplomaType = 2,
                            JobRelation = 4,
                            Location = 5,
                            School = "Howest",
                            Study = "Master in Environmental Sciences"
                        },
                        new
                        {
                            Id = 10,
                            DiplomaType = 1,
                            JobRelation = 4,
                            Location = 6,
                            School = "Université de Liège",
                            Study = "Computer Science"
                        },
                        new
                        {
                            Id = 11,
                            DiplomaType = 2,
                            JobRelation = 5,
                            Location = 7,
                            School = "Université de Namur",
                            Study = "Master in Physics"
                        },
                        new
                        {
                            Id = 12,
                            DiplomaType = 0,
                            JobRelation = 5,
                            Location = 8,
                            School = "Haute École Louvain en Hainaut",
                            Study = "Multimedia Production"
                        },
                        new
                        {
                            Id = 13,
                            DiplomaType = 1,
                            JobRelation = 6,
                            Location = 9,
                            School = "Université de Mons",
                            Study = "Industrial Engineering"
                        },
                        new
                        {
                            Id = 14,
                            DiplomaType = 2,
                            JobRelation = 7,
                            Location = 10,
                            School = "Hogeschool Odisee",
                            Study = "Master in Artificial Intelligence"
                        },
                        new
                        {
                            Id = 15,
                            DiplomaType = 0,
                            JobRelation = 8,
                            Location = 11,
                            School = "C-Mine Crib",
                            Study = "Digital Marketing"
                        },
                        new
                        {
                            Id = 16,
                            DiplomaType = 1,
                            JobRelation = 9,
                            Location = 12,
                            School = "Howest",
                            Study = "Product Design"
                        },
                        new
                        {
                            Id = 17,
                            DiplomaType = 2,
                            JobRelation = 9,
                            Location = 13,
                            School = "VIVES University College",
                            Study = "Master in Marine Biology"
                        },
                        new
                        {
                            Id = 18,
                            DiplomaType = 0,
                            JobRelation = 9,
                            Location = 14,
                            School = "HoGent",
                            Study = "Web Development"
                        },
                        new
                        {
                            Id = 19,
                            DiplomaType = 1,
                            JobRelation = 9,
                            Location = 15,
                            School = "Thomas More",
                            Study = "International Business"
                        },
                        new
                        {
                            Id = 20,
                            DiplomaType = 2,
                            JobRelation = 9,
                            Location = 16,
                            School = "Haute École de la Province de Hainaut Condorcet",
                            Study = "Master in Environmental Engineering"
                        },
                        new
                        {
                            Id = 21,
                            DiplomaType = 1,
                            JobRelation = 10,
                            Location = 17,
                            School = "Hogeschool Gent",
                            Study = "Applied Mathematics"
                        },
                        new
                        {
                            Id = 22,
                            DiplomaType = 2,
                            JobRelation = 10,
                            Location = 18,
                            School = "Howest",
                            Study = "Master in Industrial Design"
                        },
                        new
                        {
                            Id = 23,
                            DiplomaType = 1,
                            JobRelation = 11,
                            Location = 19,
                            School = "Haute École de la Province de Liège",
                            Study = "Electrical Engineering"
                        },
                        new
                        {
                            Id = 24,
                            DiplomaType = 0,
                            JobRelation = 12,
                            Location = 20,
                            School = "Thomas More",
                            Study = "Graphic Design"
                        },
                        new
                        {
                            Id = 25,
                            DiplomaType = 1,
                            JobRelation = 12,
                            Location = 21,
                            School = "HEPH-Condorcet",
                            Study = "Industrial Automation"
                        },
                        new
                        {
                            Id = 26,
                            DiplomaType = 2,
                            JobRelation = 12,
                            Location = 22,
                            School = "Université catholique de Louvain",
                            Study = "Master in Civil Engineering"
                        },
                        new
                        {
                            Id = 27,
                            DiplomaType = 1,
                            JobRelation = 13,
                            Location = 23,
                            School = "Hogeschool VIVES",
                            Study = "Tourism and Leisure Management"
                        },
                        new
                        {
                            Id = 28,
                            DiplomaType = 2,
                            JobRelation = 14,
                            Location = 24,
                            School = "Vrije Universiteit Brussel",
                            Study = "Master in Neuroscience"
                        },
                        new
                        {
                            Id = 29,
                            DiplomaType = 1,
                            JobRelation = 14,
                            Location = 25,
                            School = "Erasmushogeschool Brussel",
                            Study = "Culinary Arts"
                        },
                        new
                        {
                            Id = 30,
                            DiplomaType = 2,
                            JobRelation = 15,
                            Location = 26,
                            School = "Hogeschool PXL",
                            Study = "Master in Archaeology"
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Testamonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Testamonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 1,
                            JobTitel = "QA Enigneer consultant",
                            Name = "Luca Hendrickx"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. As a QA Engineer, I've had the opportunity to work on challenging projects and collaborate with a talented team.",
                            JobId = 2,
                            JobTitel = "QA Engineer",
                            Name = "QA Engineer 1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Working as a Business Analyst, I've been involved in critical analysis and decision-making, contributing to the success of the organization.",
                            JobId = 3,
                            JobTitel = "Business Analyst",
                            Name = "Business Analyst 1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. As a QA Engineer, I've had the opportunity to work on innovative projects and contribute to the continuous improvement of software quality.",
                            JobId = 4,
                            JobTitel = "QA Engineer",
                            Name = "QA Engineer 2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Being a Business Analyst, I've played a key role in aligning business goals with technological solutions, ensuring successful project outcomes.",
                            JobId = 5,
                            JobTitel = "Business Analyst",
                            Name = "Business Analyst 2"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 6,
                            JobTitel = "Helpdesk",
                            Name = "Helpdesk 1"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 7,
                            JobTitel = "PHP Developer",
                            Name = "PHP Developer 1"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 8,
                            JobTitel = "Drupal Developer",
                            Name = "Drupal Developer 1"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 9,
                            JobTitel = "Cobol Developer",
                            Name = "Cobol Developer 1"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 10,
                            JobTitel = "Dynammics Developer",
                            Name = "Dynammics Developer 1"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 11,
                            JobTitel = "Java Developer",
                            Name = "Java Developer 1"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 12,
                            JobTitel = "SAP Developer",
                            Name = "SAP Developer 1"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 13,
                            JobTitel = "Siebel Developer",
                            Name = "Siebel Developer 1"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 14,
                            JobTitel = "RPG developer",
                            Name = "RPG developer 1"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 15,
                            JobTitel = "System admin",
                            Name = "System admin 1"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 16,
                            JobTitel = "Network engineer",
                            Name = "Network engineer 1"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 17,
                            JobTitel = "Data migration expert",
                            Name = "Data migration expert 1"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 18,
                            JobTitel = "Data architect",
                            Name = "Data architect 1"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 19,
                            JobTitel = "Database administrator",
                            Name = "Database administrator 1"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 20,
                            JobTitel = "AWS DevOps Engineer",
                            Name = "AWS DevOps Engineer 1"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 21,
                            JobTitel = "Project manager",
                            Name = "Project manager 1"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 22,
                            JobTitel = "Azure DevOps Engineer",
                            Name = "Azure DevOps Engineer 1"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 23,
                            JobTitel = "SharePoint Developer",
                            Name = "SharePoint Developer 1"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 24,
                            JobTitel = ".NET Developer",
                            Name = ".NET Developer 1"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 25,
                            JobTitel = "Frontend Developer",
                            Name = "Frontend Developer 1"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 26,
                            JobTitel = "Software Architect",
                            Name = "Software Architect 1"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 27,
                            JobTitel = "Development Team Lead",
                            Name = "Development Team Lead 1"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 28,
                            JobTitel = "SCRUM Master",
                            Name = "SCRUM Master 1"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 29,
                            JobTitel = "Security Engineer",
                            Name = "Security Engineer 1"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            JobId = 30,
                            JobTitel = "PEN Tester",
                            Name = "PEN Tester 1"
                        });
                });

            modelBuilder.Entity("StudyGuidance.Domain.Option", b =>
                {
                    b.HasOne("StudyGuidance.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyGuidance.Domain.Testamonial", b =>
                {
                    b.HasOne("StudyGuidance.Domain.Job", null)
                        .WithOne("Testamonial")
                        .HasForeignKey("StudyGuidance.Domain.Testamonial", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyGuidance.Domain.Job", b =>
                {
                    b.Navigation("Testamonial")
                        .IsRequired();
                });

            modelBuilder.Entity("StudyGuidance.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
