name: Run Gatling Enterprise Simulation
env:
  SIMULATION_ID: 'c3acaf60-a052-4f48-9e3d-b68dd28f92e1'


on:
  push:
    branches:
      - devops

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Gatling Enterprise Action
        uses: gatling/enterprise-action@v1
        with:
          api_token: ${{ secrets.GATLING_ENTERPRISE_API_TOKEN }}
          simulation_id: ${{ env.simulation_id }}
        
      - run: |
          echo "reports_url=${{ steps.enterprise-action.outputs.reports_url }}"
