name: Gatling load test
env:
  TEST_PATH: './GatlingTests'

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy StudyGuidance T4T"]
    types:
      - completed
  push:
    branches:
      - development
      - devops

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: run gatling tests
        run: |
          mvn gatling:test
        env: 
          GATLING_SIMULATIONS_FOLDER: "#{{ env.TEST_PATH }}"

      - name: Archive Gatling results
        uses: actions/upload-artifact@v2
        with:
          name: gatling-results
          path: target/gatling