name: Build and deploy StudyGuidance T4T
env:
  AZURE_WEBAPP_NAME_FRONTEND: StudyGuidanceWebApp
  AZURE_WEBAPP_NAME_BACKEND: StudyGuidanceWebApp

  WORKING_DIRECTORY_FRONTEND: '.\StudyGuidance\StudyGuidance.Web'
  WORKING_DIRECTORY_BACKEND: '.\StudyGuidance\StudGuidance.Api'
  
  AZURE_WEBAPP_PACKAGE_PATH_FRONTEND: './publish'
  AZURE_WEBAPP_PACKAGE_PATH_BACKEND: './publish_backend'
  DOTNET_VERSION: '6.0'
  CONFIGURATION: Release
  AZURE_CORE_OUTPUT: 'none'

on:
  push:
    branches:
    - development
    - devops
  pull_request:
    types:
    - closed
    branches:
    - development
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'development'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY_FRONTEND }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY_FRONTEND }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY_FRONTEND }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}"
    
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp-frontend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}


      - name: Restore-backend
        run: dotnet restore "${{ env.WORKING_DIRECTORY_BACKEND }}"

      - name: Set Database connection_string
        run: sed -i 's|"Data Source=(localdb)\\\\MSSQLLocalDB;Database=StudyGuidanceDb;Integrated Security=True;TrustServerCertificate=True;"|"${{ secrets.CONNECTION_STRING_DEVELOPMENT }}"|g' ./StudyGuidance/StudGuidance.Api/appsettings.json

      - name: build-backend
        run: dotnet build "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish-backend
        run: dotnet publish "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}"


      - name: Publish Artifacts Frontend
        uses: actions/upload-artifact@v3
        with:
          name: webapp-backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}

      - name: Publish Artifacts Backend
        uses: actions/upload-artifact@v3
        with:
          name: webapp-backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}

      - name: ls -la
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  


