name: Build and deploy StudyGuidance T4T
env:
  AZURE_WEBAPP_NAME_FRONTEND: StudyGuidanceWebApp
  AZURE_WEBAPP_NAME_BACKEND: StudGuidanceApi

  WORKING_DIRECTORY_FRONTEND: '.\StudyGuidance\StudyGuidance.Web'
  WORKING_DIRECTORY_BACKEND: '.\StudyGuidance\StudGuidance.Api'
  
  AZURE_WEBAPP_PACKAGE_PATH_FRONTEND: './publish'
  AZURE_WEBAPP_PACKAGE_PATH_BACKEND: './publish_backend'

  FRONTEND_URL_LOCATTION: './StudyGuidance/StudyGuidance.Web/ApiClient/'
  BACKEND_URL: 'https://studguidanceapi.azurewebsites.net/api/Quiz'
  DOTNET_VERSION: '6.0'
  CONFIGURATION: Release
  AZURE_CORE_OUTPUT: 'none'

on:
  push:
    branches:
    - development
    - devops
  pull_request:
    types:
    - closed
    branches:
    - development
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'development'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}


      - name: Set Database connection_string
        run: sed -i 's|"Data Source=(localdb)\\\\MSSQLLocalDB;Database=StudyGuidanceDb;Integrated Security=True;TrustServerCertificate=True;"|"Server=tcp:studyguidancedb.database.windows.net,1433;Initial Catalog=StudyGuidance;Persist Security Info=False;User ID=super;Password=${{secrets.DATABASE_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"|g' ./StudyGuidance/StudGuidance.Api/appsettings.json
  

      - name: Restore-backend
        run: dotnet restore "${{ env.WORKING_DIRECTORY_BACKEND }}"

      - name: build-backend
        run: dotnet build "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish-backend
        run: dotnet publish "${{ env.WORKING_DIRECTORY_BACKEND }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}"



      - name: Publish Artifacts Backend
        uses: actions/upload-artifact@v3
        with:
          name: webapp-backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      

      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}

      
      - name: deployment-backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}

