name: Selenium End-to-End Test
env:
  TEST_PATH: './Team4Talent-StudyGuidanceAutomationTests'
on:
  workflow_dispatch:
  push:
    branches:
    - devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          
      - name: Build Maven project
        run: mvn package
        working-directory: TEST_PATH

      - name: Run Selenium tests
        run: mvn clean test
        working-directory: TEST_PATH

      - name: Create test report
        run: mvn surefire-report:report-only
        working-directory: TEST_PATH

      - name: Upload Surefire HTML report
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report
          path: ./Team4Talent-StudyGuidanceAutomationTests/target/site/surefire-report.html